Document: timeit
Title: Debian timeit Manual
Author: <insert document author here>
Abstract: This manual describes what timeit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/timeit/timeit.sgml.gz

Format: postscript
Files: /usr/share/doc/timeit/timeit.ps.gz

Format: text
Files: /usr/share/doc/timeit/timeit.text.gz

Format: HTML
Index: /usr/share/doc/timeit/html/index.html
Files: /usr/share/doc/timeit/html/*.html
