#!/bin/bash


git --no-pager diff --no-ext-diff  -U0 $(
git merge-base --fork-point $(git show-branch \
| sed "s/].*//" \
| grep "\*" \
| grep -v "$(git rev-parse --abbrev-ref HEAD)" \
| head -n1 \
| sed "s/^.*\[//"))
