name: Checks

on:
  pull_request:
    branches: [ "master" ]

jobs:
  unit-tests:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Install libs
        run: sudo apt-get install -y
          libgtkmm-3.0-dev
          libxss-dev
          libsqlite3-dev
          gtkmm-3.0-dev
          libjansson-dev
          libcurl4-openssl-dev
          libx11-dev
          gettext
          libfmt-dev
          libnotify-dev
          libgtest-dev
          cmake
          ninja-build
          gcc
          clang-tidy

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2

      - name: Show build environment
        run: |
          set -x
          pwd
          id
          env
          cmake --version
          ninja --version
          gcc --version
          git status
          git log -1

      - name: Configure cmake
        run: cmake --preset ninja-multi -DDISABLE_CLANG_TIDY=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build TimeIT
        run: cmake --build --preset ninja-multi-debug

      - name: Unit tests
        id: unit_test
        run: builds/ninja-multi/src/tests/Debug/tests

      - name: Analyze with clang-tidy
        run: |
          git --no-pager diff -U0 HEAD^ | clang-tidy-diff -p1 -path builds/ninja-multi -export-fixes clang-fixes.yaml

      - name: Show fixes
        run: |
          cat clang-fixes.yaml

      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@master
        with:
          # The GitHub token (or a personal access token)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path to the clang-tidy fixes generated previously
          clang_tidy_fixes: clang-fixes.yaml
          # Optionally set to true if you want the Action to request
          # changes in case warnings are found
          request_changes: true
          # Optionally set the number of comments per review
          # to avoid GitHub API timeouts for heavily loaded
          # pull requests
          suggestions_per_comment: 10
